### ISSUE TITLE
Doesn't seem to work for "Rmd" R markdown files

### ISSUE THREAD

**Issue by pavopax** [whomwah/qlstephen#104]
Do other find that QLStephen works for Rmd files?

It doesn't work for me. I tried after cleaning cache and relaunching Finder.

I don't want to install the overkill [hrbrmstr/QuickLookR](https://github.com/hrbrmstr/QuickLookR)

Does QLStephen work for .Rmd files for others? How did you make it so? Is it possible to add arbitrary extensions so that QLStephen recognizes them?

Thanks all!

EDIT: Current behavior is no preview of Rmd files. Quicklook only shows Rmd file icon, instead of any text preview. Also, I have this from `qlmanage -m`:

`public.data -> /Users/paczuskp/Library/QuickLook/QLStephen.qlgenerator (1.5.1)`

**Comment by EJFuchs** [comment]
I have the same issue with .Rmd, .R and .fasta files.  they are all text files but QuickLook cannot see them.  My system defaults to TextEdit as the opening program, which makes me suggest that they are recognized as text files, however quicklook doesn't work.

have any of you found a work around?

**Comment by pavopax** [comment]
I was able to get this to work by piecing together the relevant instructions from another issue.

See my comment there: https://github.com/whomwah/qlstephen/issues/87#issuecomment-831399689
