### ISSUE TITLE
I can't install QLStephen with brew.

### ISSUE THREAD

**Issue by Ethan00Si** [whomwah/qlstephen#107]
<img width="730" alt="截屏2020-11-24 下午12 20 05" src="https://user-images.githubusercontent.com/48440583/100048291-71b65180-2e4f-11eb-87a4-55114b7ff343.png">

Error: Cask 'qlstephen' is unavailable: No Cask with this name exists.

**Comment by xiebruce** [comment]
don't you cask, use `brew install qlstephen`, it should be work.

**Comment by Ethan00Si** [comment]
> don't you cask, use `brew install qlstephen` directly, it should be work.

not working

**Comment by xiebruce** [comment]
> > don't you cask, use `brew install qlstephen` directly, it should be work.
> 
> not working

can you post the error info screenshot here?

**Comment by Ethan00Si** [comment]
> > > don't you cask, use `brew install qlstephen` directly, it should be work.
> > 
> > 
> > not working
> 
> can you post the error info screenshot here? BTW, what's your macOS version?

<img width="560" alt="截屏2020-12-06 下午9 52 19" src="https://user-images.githubusercontent.com/48440583/101281983-519e6f00-380d-11eb-8353-7ca2d7540b57.png">

catalina 10.15.5

**Comment by xiebruce** [comment]
My macOS version is: `Mojave 10.14.4`
My Homebrew version is: `2.6.0-104-g24f7898`

I install just now and it works
![image](https://user-images.githubusercontent.com/13575500/101281955-29167500-380d-11eb-8596-0b25cf8deb7c.png)

 I don't know if it's related to the macOS version, but I suggest you update homebrew first(run `brew update`)

**Comment by Ethan00Si** [comment]
Although I don't fix it, I decide to forgive it. But, thanks for your help!

**Comment by ivanreese** [comment]
I installed from cask using the new brew syntax, and that worked:

```
brew install --cask qlstephen
```
