### ISSUE TITLE
tries to render ePubs?

### ISSUE THREAD

**Issue by tjluoma** [whomwah/qlstephen#30]
This plugin seems to be trying to show me .epub files, which of course does not work well.

Screenshot attached

![omnioutliner 4](https://f.cloud.github.com/assets/26965/1946666/10a627d4-801a-11e3-929e-5365639a4dc0.jpg)

When I removed `qlstephen` from ~/Library/QuickLook/ the epub went back to showing its normal iBooks icon.

Mac OS X 10.9.1

**Comment by Arcami** [comment]
Is this still working? Because i couldn't find the file.
Is there any other way to blacklist a custom extension?

**Comment by zmwangx** [comment]
Create the file if it's not present. I have an example at https://gist.github.com/zmwangx/cf16a5e2ac17e898f48d

**Comment by Arcami** [comment]
Thank you for your fast reply.
I tried it several times with no success.
I'm running Mavericks.

**Comment by zmwangx** [comment]
You have to run `qlmanage -r` after editing the file.

**Comment by Arcami** [comment]
I did that. I also killed finder and rebooted the system. And installed the plugin in /Library/Quicklook and  ~/Library/Quicklook one after the other and then both at the same time. Nothing it's working.
I don't know what I'm doing wrong.

**Comment by zmwangx** [comment]
You can try to debug with `qlmanage -p -d<debug_level> <filename>`. Can't offer much insight on that, sorry. I never had any problem with the black list.

**Comment by Arcami** [comment]
Okay, thank you for helping me, much appreciated.

**Comment by incandescentman** [comment]
Adding to the `QLStephen.qlgenerator/Contents/Resources/QLStephenExtensionsBlackList.plist` blacklist worked for me.

**Comment by tsdorsey** [comment]
#37 Adds a new feature by @comawill that limits the preview to the first 100KB. This will speed up rendering of large files. This is not a complete solution but does remove some of the pain.

**Comment by tsdorsey** [comment]
Consolidated to #87
