### ISSUE TITLE
.DS_Store hangs/crash on Yosemite

### ISSUE THREAD

**Issue by mafrost** [whomwah/qlstephen#34]
In Yosemite, (never happened for me in Mavericks and before) Finder hangs when quick look tries to open .DS_Store files. I've tried adding .DS_Store to blacklist but it doesn't work. No matter if I restart computer or whatever it hangs everytime I try to quick look a .DS_Store.

**Comment by kevinSuttle** [comment]
Works for me! Thanks!

**Comment by tsdorsey** [comment]
I no longer saw this issue on OSX 10.11.4 but #39 should make sure it never comes back.
