### ISSUE TITLE
whitelist?

### ISSUE THREAD

**Issue by incandescentman** [whomwah/qlstephen#45]
How do I get Stephen to QuickLook only file types listed in the whitelist and blacklist everything else? 

Right now when I (single) click on a `.sh` file in the Finder, Finder tries to execute it, then crashes. I've been adding more and more file types to my `QLStephenExtensionsBlackList.plist` but it's tedious having to add everything. 

Also I tried adding `sh` to the blacklist and Finder still tries to execute it the file. 

As far as I can tell, this behavior is not caused by my other QuickLook plugins: BetterZipQL, QLStephen, Suspicious Package, epub, QuickLookCSV, webp,QLPrettyPatch, quicklookjson, and aa_epub. 

How do I solve this?

**Comment by tsdorsey** [comment]
I'm not seeing this behavior with QLStephen installed. I have a shell script that is marked as executable I'm testing with. Here is my list of plugins I have installed:

BetterZipQL.qlgenerator
QLColorCode.qlgenerator
QLMarkdown.qlgenerator
QLPrettyPatch.qlgenerator
QLStephen.qlgenerator
QuickLookCSV.qlgenerator
QuickLookJSON.qlgenerator
WebP.qlgenerator

Have you removed QLStephen and made sure the behavior goes away?

**Comment by jjarava** [comment]
Hi! 
Had a similar issue (https://github.com/digitalmoksha/QLCommonMark/issues/1) and the root issue were that ITUs were messed up.

Looking around, I found https://www.cocoanetics.com/2012/09/fun-with-uti/ and https://superuser.com/questions/263311/on-os-x-how-do-you-change-a-files-kind

To make a long story short, resetting the UTI database seemed to sort things out:

`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user`
