### ISSUE TITLE
Could not determine attribtues of file 

### ISSUE THREAD

**Issue by anaderi** [whomwah/qlstephen#49]
Hi!

as I try to quick look such file

```
cat > test << EOF
1.1 Видим возрастание (вроде как линейное)
1.2 Чем больше людей, тем более пологий график. Когда людей на рынке под 500, за 200 шагов даже не все успевают разориться
EOF
```

I get the error

```
29.05.16 22:24:09,584 QuickLookSatellite[58500]: QLStephen: Could not determine attribtues of file file:///....
```

if I `head -1 test > test2`, then can see the preview just fine. 
What am I doing wrong here? How can I view the 1st file?

NB: maybe worht updating error message s/attribtues/attributes/ )

**Comment by tsdorsey** [comment]
I don't think you're doing anything wrong. What is your system language set to?

For posterity I ran the first `cat` command and got the `test` file as expected. Preview fails to render and I get the same error message. Running the `head` command I get `test2` but with only the first line `1.1 Видим возрастание (вроде как линейное)` in it and the preview renders. Running `head test > test3` results in a file with the same size as `test` and the preview has the same error.

I'll look into this. Give me a couple days.

**Comment by anaderi** [comment]
system language is Russian.
