### ISSUE TITLE
brew cask install does not work

### ISSUE THREAD

**Issue by PEZO19** [whomwah/qlstephen#53]
brew cask install qlstephen
==> Downloading https://github.com/downloads/whomwah/qlstephen/QLStephen.qlgenerator.zip
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'qlstephen' with message: Download failed: https://github.com/downloads/whomwah/qlstephen/QLStephen.qlgenerator.zip

**Comment by rinopo** [comment]
It's working for me.

The current cask should download from the following URL: https://github.com/whomwah/qlstephen/releases/download/1.4.3/QLStephen.qlgenerator.1.4.3.zip

Have you tried `brew update` before `brew cask install` ?

cf. https://github.com/caskroom/homebrew-cask/pull/20643/commits/166aa4ef0f5007fd553ef42720dd59f5a78c53a6

**Comment by PEZO19** [comment]
Yes it was `brew update`, ty.
