### ISSUE TITLE
Turn off for specific filetypes?

### ISSUE THREAD

**Issue by fourquarts** [whomwah/qlstephen#64]
I'd like to be able to turn off qlstephen for certain types of files, such as .savedsearch files. I don't think this is currently possible, but I'd like to request it as a feature. If it is already available, is there a guide that explains how to make use of this functionality? (I couldn't find one.)

Thanks!

**Comment by tsdorsey** [comment]
It's not possible at the moment. PR to add settings like this are welcome. Right now there is no easy way to configure settings of any kind for this plugin.

**Comment by SainteCelery** [comment]
There's no easy way to do it, but you can totally go into the plist and delete the entries for extensions you don't want it to read. Also, macOS reads QLPlugins in alphabetical order so you could try renaming a different plugin AAWhatever so it comes up before QLStephen if you're trying to get it to be the one to ql the file type. Apple provides info about how to troubleshoot qlplugins; in terminal you can just use the qlmanage actions shown [here](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/Quicklook_Programming_Guide/Articles/QLDebugTest.html#//apple_ref/doc/uid/TP40005020-CH14-SW4).
