### ISSUE TITLE
Paint 2 app interfering with Quicklook

### ISSUE THREAD

**Issue by schumannd** [whomwah/qlstephen#66]
QLstephen wasn't working so I checked:

`qlmanage -d1 -p /Users/mac/.bash_history`

Which returned the following error:
```
Testing Quick Look preview with files:
	/Users/mac/.bash_history
[DEBUG] Preview test for file:///Users/mac/.bash_history. Content type UTI: public.data
[DEBUG] Previewing file:///Users/mac/.bash_history. Content type UTI: public.data. Generator used: <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator>
[DEBUG] Loading <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator>
[DEBUG] Previewing file:///Users/mac/.bash_history did not produce anything
[DEBUG] Thumbnailing file:///Users/mac/.bash_history - type: public.data - generator: <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Users/mac/.bash_history. Content type UTI: public.data. Generator used: <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator>
[DEBUG] Thumbnailing file:///Users/mac/.bash_history did not produce anything
2017-10-18 16:05:26.603 qlmanage[4422:297445] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9507, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-10-18 16:05:26.675 qlmanage[4422:297445] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xd73b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-10-18 16:05:26.676 qlmanage[4422:297445] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa707, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

Deleting the Paint 2 app "solved" the issue. Can one prevent random apps interfering with the plugin?

**Comment by tsdorsey** [comment]
Not easily. The purpose of the very generic content type UTI in QLStephen is to play nice with other well behaved QL plugins. For a more in depth explanation check out [my comment on this other issue](https://github.com/whomwah/qlstephen/issues/57#issuecomment-255242134).

If QLStephen starts registering for more specific types the burden to "be all things to all file types" problem sets in. QLStephen is intended to catch the things that fall through the cracks. Besides, there are already [great options](https://github.com/sindresorhus/quick-look-plugins) out there taking on specific use cases.

In your case you have an app that probably not well behaved (I doubt that Paint 2 really wants to support QL of all file types). I suggest bringing it their attention. If you need Paint 2 installed you could try the same approach that I outlined at the end of that thread (linked above) to disable the Paint 2 QL plugin.
