### ISSUE TITLE
Renders Smart Folders as txt files

### ISSUE THREAD

**Issue by asafch** [whomwah/qlstephen#67]
I have a Smart folder on the desktop, and after installing this package, the folder icon appears as a `txt` file (the contents are actually `xml`) rather than the original violet color.

**Comment by tsdorsey** [comment]
I have this plugin installed and just made a new `smart folder` and it shows up as a violet folder... What happens if you make a new smart folder now that the plugin is installed?

**Comment by foxfluff** [comment]
Even when making a new smart folder, this behaviour is being shown where all smart folders are rendered as txt files instead of the standard violet geared folder
