### ISSUE TITLE
Cannot quicklook text files with .txt extensions

### ISSUE THREAD

**Issue by erdtsksn** [whomwah/qlstephen#68]
I try to add following code but it doesn't work.

```
<key>LSItemContentTypes</key>
<array>
    <string>public.data</string>
    <string>public.plain-text</string>
</array>
```

My OS: macOS High Sierra
Installation Method: Homebrew

Screenshots:
<img width="700" alt="test_with_txt" src="https://user-images.githubusercontent.com/22197800/33571982-b2151028-d942-11e7-891d-fb60459e2a24.png">

<img width="924" alt="test_without_ext" src="https://user-images.githubusercontent.com/22197800/33571983-b239d9ee-d942-11e7-9922-ab98eb615cfa.png">

**Comment by SainteCelery** [comment]
I was having the same issue. For me, QLColorCode was the culprit. 

In Terminal, try:

# Which plugins read this **kind** of file? (In this situation the KIND variable would be **text**.)#

`qlmanage -m plugins | grep **KIND**`

&/OR:

# Which ql plugin reads **this file**? #

`qlmanage -d4 -p '**/path/to/file.extension**'`

Also, useful:

# What file types does **this ql plugin** see? #

`qlmanage -debuglevel 4 **/path/to/Library/Quicklook/plugin.qlgenerator**`

**Comment by erdtsksn** [comment]
```
└─[ ✓ ] λ qlmanage -m plugins | grep text
  net.multimarkdown.text -> /Users/erdtsksn/Library/QuickLook/QLMarkdown.qlgenerator (1.3.3)
  com.foldingtext.foldingtext.document -> /Users/erdtsksn/Library/QuickLook/QLMarkdown.qlgenerator (1.3.3)
  public.plain-text -> /Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator (2.0.9 - loaded)
  public.text -> /Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator (2.0.9 - loaded)
  public.comma-separated-values-text -> /Users/erdtsksn/Library/QuickLook/QuickLookCSV.qlgenerator (1.3)
  public.tab-separated-values-text -> /Users/erdtsksn/Library/QuickLook/QuickLookCSV.qlgenerator (1.3)
  org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (743.7 - loaded)
  com.apple.finder.textclipping -> /System/Library/QuickLook/Clippings.qlgenerator (743.7)
```

```
└─[ ✓ ] λ qlmanage -d4 -p ~/Desktop/test.txt      
Testing Quick Look preview with files:
	/Users/erdtsksn/Desktop/test.txt
[DEBUG] Registering <QLGenerator Web.qlgenerator> for com.apple.webarchive
...
# Registering others
....
[DEBUG] Preview test for file:///Users/erdtsksn/Desktop/test.txt. Content type UTI: public.plain-text
[DEBUG] Previewing file:///Users/erdtsksn/Desktop/test.txt. Content type UTI: public.plain-text. Generator used: <QLGenerator /Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator>
[DEBUG] Loading <QLGenerator /Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator>
go4it:9: permission denied: /usr/local/opt/highlight/bin
go4it:9: permission denied: /usr/local/opt/highlight/bin
2017-12-10 17:56:53.005 qlmanage[7606:1105700] QLColorCode: colorize.sh failed with exit code 101.  Command was ('/Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator/Contents/Resources/colorize.sh' '/Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator/Contents/Resources' '/Users/erdtsksn/Desktop/test.txt' 0).
[DEBUG] Previewing file:///Users/erdtsksn/Desktop/test.txt did not produce anything
[DEBUG] Thumbnailing file:///Users/erdtsksn/Desktop/test.txt - type: public.plain-text - generator: <QLGenerator /Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Users/erdtsksn/Desktop/test.txt. Content type UTI: public.plain-text. Generator used: <QLGenerator /Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator>
go4it:5: permission denied: /usr/local/opt/highlight/bin
go4it:5: permission denied: /usr/local/opt/highlight/bin
2017-12-10 17:56:53.123 qlmanage[7606:1105700] QLColorCode: colorize.sh failed with exit code 101.  Command was ('/Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator/Contents/Resources/colorize.sh' '/Users/erdtsksn/Library/QuickLook/QLColorCode.qlgenerator/Contents/Resources' '/Users/erdtsksn/Desktop/test.txt' 1).
[DEBUG] Thumbnailing file:///Users/erdtsksn/Desktop/test.txt did not produce anything
2017-12-10 17:56:53.164 qlmanage[7606:1105700] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7503, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-12-10 17:56:53.307 qlmanage[7606:1105700] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x13837, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

It looks like something is wrong with permission.

**Comment by sea200k** [comment]
I have the similar issue. Is there any alternative solutions? I don't want to remove QLColorCode, since is    really of great use

**Comment by sea200k** [comment]
I found a solution in the QLColorCode issues:

At the command line type `which highlight`. Put the resulting path into the command `defaults write org.n8gray.QLColorCode pathHL /path/to/your/highlight`.

**Comment by chrise86** [comment]
I just uninstalled QLColorCode after reading @SainteCelery's comment above, which fixed the issue for me. Then read @sea200k's comment about setting the path to highlight, so reinstalled QLColorCode and some how it's just working on it's own ¯\_(ツ)_/¯

**Comment by gtalarico** [comment]
I was having the same issue. 
Removing and reinstalling QLColorCode fixed it for me,

I noticed in my mac bootstraping code, QLColorCode was being installed first first.
Could the order of installation affect it? (eg should installing QLStephen first)

**Comment by jcstorino** [comment]
I've done all the outbreaks here, but some files are simply not, even though they are of the same extension.
![image](https://user-images.githubusercontent.com/19559870/98702099-c5f20980-2358-11eb-8470-7106254039e0.png)

This file with .prw extension is show ok.
![image](https://user-images.githubusercontent.com/19559870/98702167-d904d980-2358-11eb-9a24-f21ca3f66c60.png)

Other with same extension do not open
![image](https://user-images.githubusercontent.com/19559870/98702340-03569700-2359-11eb-9827-683d5dd65fc1.png)

Debuging...
![image](https://user-images.githubusercontent.com/19559870/98702306-fafe5c00-2358-11eb-86b3-0240e7384fdb.png)

Using Catalina 10.15.7 and last QLStephen from brew..
