### ISSUE TITLE
HTML code?

### ISSUE THREAD

**Issue by syberknight** [whomwah/qlstephen#69]
this is a great plugin. i hope it continues to be supported in future versions of Mac OS - i just installed it in High Sierra & it appears to be working fine.

any possibility to get it to show html files code instead of previewing it in quicklook? i love that it shows me the code for php, js, json, xml, etc; would be great to see html too.

thanks!

**Comment by tsdorsey** [comment]
Are you wanting to display the rendered HTML file? Because that should be the default behavior even with qlstephen installed. 

Found this info about tweaking the HTML quicklook behavior https://stackoverflow.com/questions/14802873/quicklook-html-files-as-text-not-rendered-html

**Comment by syberknight** [comment]
yeah, to see the code is what i'm wanting.

thanks for the link, it solved it for me!

**Comment by preyneyv** [comment]
Can we close this?
