### ISSUE TITLE
Not working for README, AUTHORS, LICENSE - text files with no extension

### ISSUE THREAD

**Issue by tklems** [whomwah/qlstephen#71]
In my case it is not working for files such: README, AUTHORS, LICENSE - text files with no extension.
macOS High Sierra. 
Latest qlstephen installed via brew cask install qlstephen.

Thank you.
Regards, 
Tomas

**Comment by tomfado** [comment]
Den 2017-12-30 kl. 23:05, skrev tklems:
> In my case it is not working for files such: README, AUTHORS, LICENSE -
> text files with no extension.
> macOS High Sierra.
> Latest qlstephen installed via brew cask install qlstephen.

It does for me with:
MacOS High Sierra Version 10.13.2, QLStephen.qlgenerator 1.4.2

regards, Tomas :-)

**Comment by tklems** [comment]
Solved. It is not a bug. Sorry...
The problem is that my macOS had several apps which registered themselves as QL generators for `public.data` type.
In that case there is no way to control which generator will be used. See: [11705425](https://stackoverflow.com/questions/11705425/prefer-my-quicklook-plugin)

To find which app is stealing the preview (e.g. for "lincence" file):
`qlmanage -d 4 -p license`

```
[DEBUG] Registering <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator> for public.data
[DEBUG] Preview test for license -- file:///Users/user/tmp/ql/. Content type UTI: public.data
[DEBUG] Previewing file:///Users/user/tmp/ql/license. Content type UTI: public.data. Generator used: <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator>
[DEBUG] Loading <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator>
[DEBUG] Previewing file:///Users/user/tmp/ql/license did not produce anything
[DEBUG] Thumbnailing license -- file:///Users/user/tmp/ql/ - type: public.data - generator: <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Users/user/tmp/ql/license. Content type UTI: public.data. Generator used: <QLGenerator /Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator>
[DEBUG] Thumbnailing file:///Users/user/tmp/ql/license did not produce anything

```

I fixed my issue by editing `Info.plist` files in .qlgenerator in the application. 
For example one of the stealer-app was: "**Paint 2**".
I changed this file:
`/Applications/Paint 2.app/Contents/Library/QuickLook/PaintQuickLook.qlgenerator/Contents/Info.plist`

Thank you.
Regards,
Tomas
