### ISSUE TITLE
Files show  instead of contents

### ISSUE THREAD

**Issue by prohtex** [whomwah/qlstephen#75]
I've run into this problem on quite a few text files. Maybe it has something to do with character encoding? Using QL on a txt file will show two "?" characters followed by the first character in the file, and nothing else.

![screen shot 2018-07-22 at 12 14 14 am](https://user-images.githubusercontent.com/12946938/43043260-7593130a-8d44-11e8-92f8-3ec8c10a755f.png)

**Comment by tsdorsey** [comment]
@prohtex I've pushed 1.5.1 with support for Catalina. Could you try this again? If you still have issues I would like a sample file to debug with.
