### ISSUE TITLE
macOS 10.15 issue

### ISSUE THREAD

**Issue by Nikkurer** [whomwah/qlstephen#96]
Hello,

I'm not sure is it a qlstephen issue but after update to macOS 10.15, it doesn't work. macOS shows a message that "QLstephen.qlgenerator cannot be opened because the developer cannot be verified."
I'll be glad if you could help me with how to fix it.

**Comment by gregplaysguitar** [comment]
See readme: https://github.com/whomwah/qlstephen#permissions-quarantine

**Comment by Nikkurer** [comment]
> See readme: https://github.com/whomwah/qlstephen#permissions-quarantine

Oh, thank you very much.
